//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace niteco_mvc_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public System.Guid id { get; set; }
        public System.Guid customer_id { get; set; }
        public System.Guid product_id { get; set; }
        public int amount { get; set; }
        public System.DateTime order_date { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string name { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
    }
}
