//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace niteco_mvc_project
{
    using System;
    using System.Collections.Generic;

    public partial class staff
    {
        public System.Guid id { get; set; }
        public string user_name { get; set; }
        public byte[] password_hash { get; set; }
        public byte[] password_salt { get; set; }
        public string name { get; set; }
        public bool? is_super_admin { get; set; }

        //[Ignore]
        public string password { get; set; }
    }
}
